### ISSUE TITLE
Feature: auto tag already printed articles

### ISSUE THREAD

**Issue by rohitkoul** [notionparallax/wp2frontEnd#39]
Once every edition is shipped and the articles show up in history, I usually manually tag all the articles in an edition with _printed_ tag. This allows me to use the pocket API to quickly check what I already have vs what I have tagged using 'wpmustprint' and other tags (and am most likely to get in upcoming edition)

It would be great if you could auto tag the printed articles. May be allow users to choose to tag that gets added to the ones that are included when an edition is locked.

**Comment by notionparallax** [comment]
Hey,
I had to make a call about using a read-only or read-write api key for Pocket, and TBH, having that much power scares me! Auto tagging needs a writeable key. _But_ you can mark your read articles pretty easily [like this](https://waldenpond.press/2021/03/17/archiving.html)

One day, when I am much more confident that I won't delete all your Pocket articles, I'll come back and add tagging to the app. I'm going to close this because it'll probably a pretty long time before I get to that point!
